#!/usr/bin/env bash
# deploy/tailscale-https-setup.sh
#
# One-time setup: issues a real TLS cert for this Pi's Tailscale hostname
# and configures Caddy to front the rf-socket-controller backend over HTTPS.
#
# Prerequisites (all available via apt on Pi OS Bookworm):
#   - tailscale   installed and connected  (tailscale status)
#   - caddy       sudo apt install -y caddy
#
# The script is idempotent — re-running it replaces the cert and Caddyfile
# with fresh copies, then reloads Caddy.
#
# Usage:
#   sudo deploy/tailscale-https-setup.sh
#   # or, if .env lives somewhere non-standard:
#   ENV_FILE=/path/to/.env sudo deploy/tailscale-https-setup.sh

set -euo pipefail

# ── helpers ─────────────────────────────────────────────────────────────────

info()  { printf '\033[1;34m→\033[0m %s\n' "$*"; }
ok()    { printf '\033[1;32m✓\033[0m %s\n' "$*"; }
die()   { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

need() {
    command -v "$1" &>/dev/null || die "'$1' not found — install with: $2"
}

# ── checks ───────────────────────────────────────────────────────────────────

[[ $EUID -eq 0 ]] || die "run as root: sudo $0"

need tailscale "curl -fsSL https://tailscale.com/install.sh | sh"
need caddy     "sudo apt install -y caddy"
need python3   "sudo apt install -y python3"

# ── resolve Tailscale FQDN ───────────────────────────────────────────────────

info "Querying Tailscale for this machine's FQDN…"
TS_STATUS=$(tailscale status --json 2>/dev/null) \
    || die "tailscale status failed — is Tailscale running? (sudo tailscale up)"

HOSTNAME=$(python3 - <<'PY'
import json, sys
d = json.loads(sys.stdin.read())
name = d.get("Self", {}).get("DNSName", "")
if not name:
    sys.exit(1)
print(name.rstrip("."))
PY
<<< "$TS_STATUS") || die "Could not determine Tailscale hostname. Run 'tailscale status' and check the output."

[[ "$HOSTNAME" == *.ts.net ]] \
    || die "Hostname '$HOSTNAME' doesn't look like a .ts.net address — is the tailnet set up?"

ok "Tailscale hostname: $HOSTNAME"

# ── check that HTTPS is enabled for this machine ─────────────────────────────

echo ""
echo "  Before continuing, make sure HTTPS is enabled for this machine"
echo "  in the Tailscale admin panel:"
echo ""
echo "    https://login.tailscale.com/admin/machines"
echo "    → click '$HOSTNAME' → '…' menu → Enable HTTPS"
echo ""
read -rp "  Press Enter when done (Ctrl-C to abort)…  "
echo ""

# ── fetch the cert ────────────────────────────────────────────────────────────

CERT_DIR=/etc/tailscale/certs
CRT_FILE="${CERT_DIR}/${HOSTNAME}.crt"
KEY_FILE="${CERT_DIR}/${HOSTNAME}.key"

info "Creating cert directory $CERT_DIR…"
mkdir -p "$CERT_DIR"

info "Fetching TLS certificate from Tailscale/Let's Encrypt…"
tailscale cert \
    --cert-file "$CRT_FILE" \
    --key-file  "$KEY_FILE" \
    "$HOSTNAME" \
    || die "'tailscale cert' failed — check that HTTPS is enabled for this machine in the admin panel."

ok "Certificate written to $CERT_DIR"

# Make the key file readable by the 'caddy' system user (Debian/Ubuntu package).
# The cert file is already world-readable; we tighten the directory so the key
# is only reachable by root and caddy.
if getent group caddy &>/dev/null; then
    chown root:caddy "$KEY_FILE"
    chmod 640        "$KEY_FILE"
    chown root:caddy "$CERT_DIR"
    chmod 750        "$CERT_DIR"
    ok "Key permissions set (root:caddy 640)"
else
    # Caddy is running as root or under a different user — leave perms as-is
    # and let the admin sort it out.
    echo "  Warning: 'caddy' group not found — key left as root:root 600."
    echo "  If Caddy fails to start, check: sudo journalctl -u caddy -n 20"
fi

# ── write Caddyfile ───────────────────────────────────────────────────────────

CADDYFILE=/etc/caddy/Caddyfile

info "Writing $CADDYFILE…"
# Back up any existing file before overwriting.
[[ -f "$CADDYFILE" ]] && cp "$CADDYFILE" "${CADDYFILE}.bak" \
    && echo "  (previous Caddyfile backed up to ${CADDYFILE}.bak)"

cat > "$CADDYFILE" << EOF
# rf-socket-controller — Tailscale HTTPS
# Generated by deploy/tailscale-https-setup.sh — re-run to regenerate.

${HOSTNAME} {
    # Forward every request to the Go backend.
    # Caddy automatically adds X-Forwarded-Proto: https so session cookies
    # get the Secure flag without any extra config in the app.
    reverse_proxy localhost:8080

    # Cert issued by Tailscale / Let's Encrypt (~90-day expiry).
    # Auto-renew with deploy/tailscale-cert-renew.sh (see cron step below).
    tls ${CRT_FILE} ${KEY_FILE}
}
EOF
ok "Caddyfile written"

# ── enable and reload Caddy ───────────────────────────────────────────────────

info "Enabling and reloading Caddy…"
systemctl enable --now caddy
systemctl reload caddy
ok "Caddy running"

# ── disable the app's built-in HTTPS (Caddy owns TLS from here) ──────────────

# Locate .env — honour ENV_FILE override, then look next to this script,
# then the common deploy location.
ENV_FILE="${ENV_FILE:-}"
if [[ -z "$ENV_FILE" ]]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    for candidate in \
        "${SCRIPT_DIR}/../.env" \
        "/home/claw/rf-socket-controller/.env" \
        "/home/pi/rf-socket-controller/.env"
    do
        if [[ -f "$candidate" ]]; then
            ENV_FILE="$(realpath "$candidate")"
            break
        fi
    done
fi

if [[ -n "$ENV_FILE" && -f "$ENV_FILE" ]]; then
    if grep -qE '^HTTPS_PORT=' "$ENV_FILE"; then
        # Comment it out — Caddy handles TLS now.
        sed -i 's|^HTTPS_PORT=|#HTTPS_PORT=|' "$ENV_FILE"
        ok "Disabled HTTPS_PORT in $ENV_FILE (Caddy handles TLS)"
        systemctl restart rf-controller
        ok "rf-controller restarted"
    else
        info "HTTPS_PORT not set in $ENV_FILE — nothing to change"
    fi
else
    echo ""
    echo "  Tip: if .env has HTTPS_PORT set, comment it out — Caddy now"
    echo "  terminates TLS so the app's built-in HTTPS listener is redundant."
fi

# ── cert auto-renewal ─────────────────────────────────────────────────────────

RENEW_SCRIPT="$(realpath "$(dirname "${BASH_SOURCE[0]}")/tailscale-cert-renew.sh")"
CRON_TARGET=/etc/cron.weekly/tailscale-cert-renew

echo ""
info "Setting up weekly cert renewal…"
if [[ -f "$RENEW_SCRIPT" ]]; then
    install -m 0755 "$RENEW_SCRIPT" "$CRON_TARGET"
    ok "Renewal cron installed at $CRON_TARGET"
else
    echo "  (deploy/tailscale-cert-renew.sh not found — install it manually)"
    echo "  sudo cp deploy/tailscale-cert-renew.sh $CRON_TARGET"
    echo "  sudo chmod +x $CRON_TARGET"
fi

# ── done ─────────────────────────────────────────────────────────────────────

echo ""
ok "All done!"
echo ""
echo "  Access the app (from any device with Tailscale) at:"
echo ""
echo "    https://${HOSTNAME}"
echo ""
echo "  No certificate warnings — it's a real Let's Encrypt cert."
echo ""
echo "  Cert expiry: ~90 days.  The weekly cron renews it automatically."
echo "  To renew manually:  sudo $CRON_TARGET"
echo ""
